---
output: github_document
editor_options: 
  chunk_output_type: console
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = ".")
  })
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "figs/",
  message = FALSE,
  warning = FALSE
)

library(nphys)
library(plotly)

```

# The nphys package 

The nphys package provides a means to import, manage, and analyze your neurophysiology data collected during electrophysiology experiments. It is geared towards developing robust and portable data management tools and analysis methods. It also serves as a tool that encourages regularly revisiting data by helping to manage large datasets and present comprehensive summaries that can be rapidly updated and opvserved from many different angles. This project is currently geared towards field long-term depression (LTD) experiments and whole-cell patch-clamp experiments, but will continue to be updated as more example datasets and methodologies become available. 

Detailed examples of how to utilize this package will be outlined in vignettes as they are updated. 




## License

This package is free and open source software.
