---
title: "nphys functions"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

library(nphys)
library(plotly)

data(field)



```


This markdown describes the origin of the traces component of the `field` rda


# Select and make averaged traces from the imported data.


```{r}



field$traces <- list(

Bl_Avg = avgSweeps(field$ABF, obs = "PreC-Bl")%>% 
    bl_adjust(.) %>% .[stimArtifact(.):(stimArtifact(.)+1500)],
Decay_Avg = avgSweeps(field$ABF, obs = "Decay") %>% bl_adjust(.) %>% 
    bl_adjust(.) %>% .[stimArtifact(.):(stimArtifact(.)+1500)],
Cond_Avg = avgSweeps(field$ABF, obs = "Cond") %>% bl_adjust(.) %>% 
    bl_adjust(.) %>% .[stimArtifact(.):(stimArtifact(.)+1500)]

)

field$traces$Time = seq(0, length.out = length(field$traces$Bl_Avg), by = field$ABF$`PreC-Bl_7`$samplingIntervalInSec*1000)   
```


# Stim Artifact function. 
adjust adds +/- to the output number for selecting range. 
```{r}
#stimA <- stimArtifact(Bl_Avg, adj = 0)
```

## Basic plotly interactive

```{r}
#Cond = FALSE
#Decay = FALSE
#Decay = TRUE


pl <- plotly::plot_ly(data = data.frame(field$traces), x = ~Time, y = ~Bl_Avg, type = "scatter", mode = "markers")%>%
  add_trace(x = ~Time, y = ~Decay_Avg) %>% 
  add_trace(x = ~Time, y = ~Cond_Avg)
# %>% 
#  layout(
#    xaxis = list(
#      title = "Time (ms)"
#    ),
#    yaxis = list(
#      range = c(-1.2,0.1),
#      title = "mV"
#    )
#  )
#    
pl

```











