---
title: "LTD Dashboard"
runtime: shiny
output:
    flexdashboard::flex_dashboard:
        vertical_layout: fill
    
---

```{r setup, include=FALSE}
#------------------ Packages ------------------
library(shiny)
library(shinydashboard)
library(nphys)
library(plotly)
`%>%` <- magrittr::`%>%`




lf <- list.files("~/nphys/dir/DGDev", pattern = "DGDev.rda", recursive = TRUE, full.names = TRUE)
tst <- unlist(fileD(lf))

tst <- gsub("-DGDev.rda", "", tst)
names(tst) = NULL

```


Column {.sidebar data-width=200}
-----------------------------------------------------------------------

### Select inpuut

```{r}

selectInput("fieldSlice", label = "Select slice:", choices = tst)
#plotOutput("plot1", click = "plot_click")





# ui <- fluidPage(
#   plotlyOutput("p"),
#   verbatimTextOutput("event")
# )


```




Column {data-width=500}
-----------------------------------------------------------------------

### field EPSP


```{r}


renderPlotly({

load(lf[grep(input$fieldSlice, lf)])
traces = as.data.frame(DGDev$traces)


 plotly::plot_ly(
         data = traces,
         x = ~ ms,
         y = ~ blTrace,
         type = "scatter",
         mode = "markers"
     )
 })


# server <- function(input, output, session) {
#   
#   output$p <- renderPlotly({
#     
#     d <- event_data("plotly_relayout", source = "trajectory")
#     
#     selected_point <- if (!is.null(d[["shapes[0].x0"]])) {
#       xint <- d[["shapes[0].x0"]]
#       xpt <- x[which.min(abs(x - xint))]
#       list(x = xpt, y = y[which(x == xpt)])
#     } else {
#       list(x = 1, y = y[which(x == 1)])
#     }
#     
#     plot_ly(color = I("red"), source = "trajectory") %>%
#       add_lines(x = x, y = y) %>%
#       add_markers(x = selected_point$x, y = selected_point$y) %>%
#       layout(
#         shapes = list(
#           type = "line", 
#           line = list(color = "gray", dash = "dot"),
#           x0 = selected_point$x, 
#           x1 = selected_point$x,
#           y0 = 0,
#           y1 = 1,
#           yref = "paper"
#         )
#       ) %>%
#       config(editable = TRUE)
#   })
#   
# }



```


